BEGIN TRANSACTION;

CREATE TABLE todos (
	id SERIAL PRIMARY KEY,
	id_user INT NOT NULL REFERENCES users(id),
	title VARCHAR(150) NOT NULL,
	completed BOOL DEFAULT false,
	created_on TIMESTAMP NOT NULL,
	done_on TIMESTAMP NULL
);

COMMIT;